# Generated by Django 6.0 on 2026-04-05 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_data', models.JSONField(help_text='Full outfit items, scores, persona from engine')),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('sport', 'Sport'), ('ethnic_festive', 'Ethnic & Festive')], default='casual', max_length=20)),
                ('persona', models.CharField(blank=True, default='', max_length=30)),
                ('total_score', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, default='', help_text="User's personal note")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_looks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
