# Generated by Django 6.0 on 2026-04-05 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wardrobe/%Y/%m/')),
                ('colour_hex', models.CharField(default='#808080', help_text='Dominant colour extracted by ColourThief', max_length=7)),
                ('colour_name', models.CharField(blank=True, default='', max_length=50)),
                ('item_type', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory')], default='top', max_length=15)),
                ('item_subtype', models.CharField(blank=True, default='', max_length=50)),
                ('pattern', models.CharField(choices=[('solid', 'Solid'), ('striped', 'Striped'), ('checked', 'Checked'), ('printed', 'Printed'), ('embroidered', 'Embroidered'), ('graphic', 'Graphic')], default='solid', max_length=15)),
                ('formality', models.PositiveSmallIntegerField(default=3, help_text='1=very casual, 5=very formal')),
                ('occasions', models.JSONField(default=list, help_text='List of applicable occasions')),
                ('is_sample', models.BooleanField(default=False)),
                ('caption', models.TextField(blank=True, default='', help_text='HF Vision generated caption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
