# Generated by Django 4.2.29 on 2026-04-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='cutout_image',
            field=models.ImageField(blank=True, help_text='Transparent PNG cutout via rembg', null=True, upload_to='wardrobe/cutouts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='Generated caption / metadata'),
        ),
    ]
